package scylla

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"path"

	"github.com/eapache/go-resiliency/retrier"
	"golang.org/x/net/publicsuffix"
)

var globalCookieJar *cookiejar.Jar

func init() {
	var err error
	globalCookieJar, err = cookiejar.New(&cookiejar.Options{
		PublicSuffixList: publicsuffix.List,
	})
	if err != nil {
		panic("unexpected error: " + err.Error())
	}
}

func WithRetryPolicy(r *retrier.Retrier) func(*Client) {
	return func(c *Client) {
		c.retry = r
	}
}

func WithUserAgent(s string) func(*Client) {
	return func(c *Client) {
		c.reqmw = append(c.reqmw, func(r *http.Request) {
			r.Header.Set("User-Agent", s)
		})
	}
}

// TraceHeader is the HTTP header carrying an external trace id. It lets the
// control plane correlate provider API calls with the stack's provisioning
// operations.
const TraceHeader = "X-Scylla-Cloud-External-Trace-Id"

// TracePrefix marks a trace id as generated by the Terraform provider rather
// than issued by ScyllaDB Cloud tooling.
const TracePrefix = "tfprovider-"

// NewTrace returns a random trace id for correlating provider API calls when
// no trace was supplied by the caller.
func NewTrace() (string, error) {
	buf := make([]byte, 16)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("failed to read random bytes: %w", err)
	}
	return TracePrefix + hex.EncodeToString(buf), nil
}

func WithTrace(s string) func(*Client) {
	if s == "" {
		return func(*Client) {}
	}

	return func(c *Client) {
		c.reqmw = append(c.reqmw, func(r *http.Request) {
			r.Header.Set(TraceHeader, s)
		})
	}
}

func WithGlobalCookieJar() func(*Client) {
	return func(c *Client) {
		c.client.Jar = globalCookieJar
	}
}

func WithCookieJar() func(*Client) {
	return func(c *Client) {
		jar, err := cookiejar.New(&cookiejar.Options{
			PublicSuffixList: publicsuffix.List,
		})
		if err != nil {
			panic("unexpected error: " + err.Error())
		}
		c.client.Jar = jar
	}
}

func WithBaseURL(s string) func(*Client) {
	return func(c *Client) {
		if s == "" {
			return
		}
		u, err := url.Parse(s)
		if err != nil {
			panic("unexpected error: " + err.Error())
		}
		c.reqmw = append(c.reqmw, func(r *http.Request) {
			if u.Scheme != "" {
				r.URL.Scheme = u.Scheme
			}
			if u.Host != "" {
				r.URL.Host = u.Host
			}
			if u.Path != "" {
				r.URL.Path = path.Join("/", u.Path, r.URL.Path)
			}
			if q := u.Query(); len(q) != 0 {
				orig := r.URL.Query()
				for k, v := range q {
					orig[k] = v
				}
				r.URL.RawQuery = orig.Encode()
			}
		})
	}
}
